### ISSUE TITLE
Equations in methods.md does not render.

### ISSUE THREAD

**Issue by aytekin-murat** [ihmeuw-msca/CurveFit#15]
Inline equations does not render. Only the following shows properly, except for the square brackets at the start and the end of each equation.

Measurement model: [
log(ytj)=pj2(1+2π−−√∫αj(t−βj)0exp(−τ2)dτ)+ϵt,j ϵt,j∼N(0,Vt)
]

(\beta)-model specification: [
βj=β+γjSj+ϵβj γj∼N(γ¯¯¯,Vγ) ϵβj∼N(0,Vβ)
]

(\alpha)-model specification: [
αj=exp(α+uαj) uα,j∼N(0,Vα)
]

(p)-model specification: [
pj=exp(p+upj) up,j∼N(0,Vp)
]

**Comment by philippemiron** [comment]
In the meantime, it's available on the documentation website: https://ihmeuw-msca.github.io/CurveFit/methods/

**Comment by mbannick** [comment]
Hello @aytekin-murat. Thanks for your comment. Our docs are meant to be viewed from the GitHub pages that @philippemiron posted above and that is linked on the repo landing page. They are rendered directly from `docs/` whenever we deploy, so please read them at https://ihmeuw-msca.github.io/CurveFit/methods/.
