### ISSUE TITLE
How to create independent variable `independent_var`

### ISSUE THREAD

**Issue by goalkeeperfyc** [ihmeuw-msca/CurveFit#35]
Hi everyone,

When taking a look at the `get_start.py`, the code for creating `independent_var` is as follow:

```python
independent_var   = np.array(range(n_data)) * beta_true / (n_data-1)
```

I am kind of confused about why the `independent_var` should be created in this way. I mean, if I change the code to this

```python
independent_var   = np.array(range(n_data))
```

The model doesn't work anymore. They fail to give me the correct parameters (`alpha, beta, p`)

I am wondering about the required format of `independent_var`. Could anyone give me any suggestions?

Thank you,
Yucheng

**Comment by mbannick** [comment]
Hi @goalkeeperfyc -- the data is simulated in a way that it matches a particular functional form between the dependent and independent variables and it tests that it gets the expected answer. For modeling a time series, the independent variable will be time. You could simulate your own example from a particular functional form that you expect off of your new independent variable and see if the model recovers the true parameters.

@bradbell wrote this example and might be able to provide more insight into what needs to change in this test if you decide to change the independent variable.

**Comment by goalkeeperfyc** [comment]
> Hi @goalkeeperfyc -- the data is simulated in a way that it matches a particular functional form between the dependent and independent variables and it tests that it gets the expected answer. For modeling a time series, the independent variable will be time. You could simulate your own example from a particular functional form that you expect off of your new independent variable and see if the model recovers the true parameters.
> 
> @bradbell wrote this example and might be able to provide more insight into what needs to change in this test if you decide to change the independent variable.

Hi Marlena,


Thank you for your explanation. But I am still confused with the independent variable. For example, if my independent variable is time (day1, day2, day3 so on so far). What should my independent variable look like?

Should they look like
```python
independent_var = np.array([1, 2, 3, 4, 5, 6,...])
```

Or I should transfer `independent_var` in some way, like
```python
independent_var = independent_var * beta / len(independent_var)
```

Thank you again for your kindly help!


Best,
Yucheng

**Comment by bradbell** [comment]
The beta should be on the same scale as the independent variable values. The maximum in the death rate occurs at day beta (for you). The multiplier alpha also has units of time. I will change the example do use days so this is simpler.

**Comment by bradbell** [comment]
I have changed the time scale to be on the order of days; see
https://bradbell.github.io/CurveFit/extract_md/get_started_xam/

**Comment by goalkeeperfyc** [comment]
> I have changed the time scale to be on the order of days; see
> https://bradbell.github.io/CurveFit/extract_md/get_started_xam/


Hi Brad, Thank you for sharing. I really appreciate it!
