### ISSUE TITLE
Use custom data to get the projection of ICU beds

### ISSUE THREAD

**Issue by luistelmocosta** [ihmeuw-msca/CurveFit#54]
I am currently working with Hospital São João, the biggest hospital in the north region of Portugal. At this moment, we are trying to project the number of ICU beds that we will be needing in the next 30 days and I was wondering if we could use your project to do that projection.

Is it possible?

**Comment by saravkin** [comment]
Hi Luis!

Portugal is on the viz, https://covid19.healthdata.org/portugal. For questions about subnational analyses, can you please contact the team at covid19@healthdata.org? 

Best wishes,
Sasha.

**Comment by luistelmocosta** [comment]
Yes, it is for subnational analysis, in this case, a regional hospital. 
I already contacted by email but it looks like they are overwhelmed and I have some urgency. I guess I will have to wait then :)

**Comment by saravkin** [comment]
Ah, I see, thanks for writing to the central address! They have a lot of requests, but if you don't hear back by tomorrow, send me an email to saravkin@uw.edu and I'll forward your message to them as well.

**Comment by luistelmocosta** [comment]
Thank you very much. Will do that. 
If you don't mind me asking, what is usually your response to this kind of request? Do you provide the code required to do the projection or you ask for data? This is relevant since this is highly sensitive data and, in my case, confidential :)

**Comment by saravkin** [comment]
I don't know how exactly the team handles new analyses requests, but I don't think they will require confidential data from you.
