### ISSUE TITLE
Methodology for May 4th update here or elsewhere?

### ISSUE THREAD

**Issue by dsjoerg** [ihmeuw-msca/CurveFit#96]
Hello, thank you for making your code available.
Is the code for the May 4th update available here or elsewhere?
Thank you, —David

**Comment by mbannick** [comment]
Hello @dsjoerg, apologies for the delay. The code for the May 4th update and the SEIIR model are not in this repository. Please see our updated [README](https://github.com/ihmeuw-msca/CurveFit/blob/master/README.md) for the links to the new code that is being used for the IHME COVID-19 forecasts.
