### ISSUE TITLE
Question about est_infections

### ISSUE THREAD

**Issue by lematt1991** [ihmeuw-msca/CurveFit#97]
Hello, I have a quick question about the forecasts available [here](http://www.healthdata.org/covid/data-downloads).  The `est_infections_*` columns seem to be very high.  For example, today's forecast shows 14,951 new cases for 2020-05-05 in New York.  I'm assuming this corresponds to the total number of cases and not just the reported or confirmed cases reported by the state.  Asking because the NYS DOH reports 2,239 new cases.  If these numbers do in fact correspond to the total number of new cases (reported and un-reported), is there any way to validate the results?

Thanks!

**Comment by mbannick** [comment]
Hi @lematt1991 thank you for your patience in our delayed response. Please contact covid19@healthdata.org for questions about the results. Also please note that this is no longer being used for IHME COVID-19 forecasting, more information in the [README](https://github.com/ihmeuw-msca/CurveFit/blob/master/README.md).
