### ISSUE TITLE
Small error in example/random_effect.py

### ISSUE THREAD

**Issue by cmsato** [ihmeuw-msca/CurveFit#98]
The `assert` for  **random** effects uses the error variable for **fixed** effects.

https://github.com/ihmeuw-msca/CurveFit/blob/2833f3a4016b939b0589f87c6784ef53e259fd61/example/random_effect.py#L214-L221

**Comment by mbannick** [comment]
@cmsato thank you for pointing this out. This should be fixed in the most recent version `1.0.0`. Please let us know if there are still issues.
