### ISSUE TITLE
Decreasing uncertainty interval

### ISSUE THREAD

**Issue by malobukov** [ihmeuw-msca/CurveFit#99]
The width of uncertainty interval for projected deaths per day is decreasing with time. This is unusual for a projection, as with most models uncertainty grows with time.

It can be driven by choosing to fit a symmetric curve, even though the actual curve is oftentimes asymmetric (e.g., in NY decrease in daily deaths is much slower than ramp-up). As a result, uncertainty interval for June 1st projection for New York now (May 10th) excludes zero, even though a couple of weeks back it was very close to zero, with very narrow uncertainty interval.

**Comment by mbannick** [comment]
Hi @malobukov thank you for your patience. Please note that the CurveFit methods and code are not being used for IHME COVID-19 forecasting at all anymore. Regarding your question about uncertainty, please see http://www.healthdata.org/covid/faqs in particular under methods/modeling.
